version: '3'
networks:
  services:
    name: services
    ipam:
      config:
        - subnet: 172.16.1.0/24
          ip_range: 172.16.1.0/24
          gateway: 172.16.1.1
services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: unless-stopped
    # docker exec -it nexus cat /nexus-data/admin.password
    volumes:
      - "./nexus/work:/sonatype-work"
      - "./nexus/data:/nexus-data"
    ports:
      - "0.0.0.0:8081:8081"
      - "0.0.0.0:8082:8082"
    ulimits:
      nproc: 65535
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          # cpus: '0.35'
          memory: 2G
    networks:
      - services