version: '3'
networks:
  services:
    name: services
    ipam:
      config:
        - subnet: 172.16.1.0/24
          ip_range: 172.16.1.0/24
          gateway: 172.16.1.1
services:
  zabbix-srv:
    image: zabbix/zabbix-server-pgsql:alpine-latest
    container_name: zabbix-srv
    ports:
    - "10051:10051"
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./monitor/alertscripts/:/usr/lib/zabbix/alertscripts
    environment:
      DB_SERVER_HOST: zabbix-db
      DB_SERVER_PORT: 5432
      POSTGRES_USER: zabbix
      POSTGRES_DB: zabbix
      POSTGRES_PASSWORD: "PSPASS"
      ZBX_CACHESIZE: 1024M
      ZBX_HISTORYCACHESIZE: 256M
      ZBX_HISTORYINDEXCACHESIZE: 256M
      ZBX_TRENDCACHESIZE: 256M
      ZBX_VALUECACHESIZE: 256M
      ZBX_STARTVMWARECOLLECTORS: 3
      ZBX_VMWAREFREQUENCY: 60
      ZBX_VMWAREPERFFREQUENCY: 60
      ZBX_VMWARECACHESIZE: 256M
      ZBX_VMWARETIMEOUT: 120
      # Environment Variables From ==>  https://www.zabbix.com/documentation/current/en/manual/installation/containers
      # Environment Variables From ==>  https://hub.docker.com/r/zabbix/zabbix-server-mysql/
      # Environment Variables From ==>  https://www.zabbix.com/documentation/current/en/manual/appendix/config/zabbix_server
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    networks:
      services:
        ipv4_address: 172.16.1.5
  #8
  zabbix-front:
    image: zabbix/zabbix-web-apache-pgsql:alpine-latest
    container_name: zabbix-front
    ports:
    - "0.0.0.0:181:8080"
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    environment:
      ZBX_SERVER_HOST: "zabbix-srv"
      DB_SERVER_HOST: "zabbix-db"
      DB_SERVER_PORT: 5432
      POSTGRES_USER: zabbix
      POSTGRES_DB: zabbix
      POSTGRES_PASSWORD: "PSPASS"
      ZBX_SESSION_NAME: "test"
      PHP_TZ: "Asia/Tehran"
      # PHP_MEMORY_LIMIT: "1024M"
      ZBX_MEMORYLIMIT: "1024M"
      ZBX_SERVER_NAME: "Monitor"
    networks:
      - services
  zabbix-db:
    image: postgres:15-alpine
    container_name: zabbix-db
    restart: unless-stopped
    volumes:
    - ./monitor/zabbix-db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_DB: zabbix
      POSTGRES_PASSWORD: PSPASS
    networks:
      - services