version: '3'
networks:
  services:
    name: services
    ipam:
      config:
        - subnet: 172.16.1.0/24
          ip_range: 172.16.1.0/24
          gateway: 172.16.1.1
services:

  guacd:
    container_name: guacd
    image: guacamole/guacd
    restart: unless-stopped
    volumes:
    - ./guacd/drive:/drive:rw
    - ./guacd/record:/record:rw
    networks:
      - services

  postgres_guacamole:
    container_name: postgres_guacamole
    restart: unless-stopped
    image: postgres:15.2-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
    volumes:
    - ./postgres_guacamole/init:/docker-entrypoint-initdb.d:z
    - ./postgres_guacamole/data:/var/lib/postgresql/data:Z
    networks:
      - services

  guacamole:
    container_name: guacamole
    restart: unless-stopped
    image: guacamole/guacamole
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres_guacamole
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
    links:
    - guacd
    ports:
      - 0.0.0.0:8080:8080/tcp
    networks:
      - services
