version: '3'
networks:
  services:
    name: services
    ipam:
      config:
        - subnet: 172.16.1.0/24
          ip_range: 172.16.1.0/24
          gateway: 172.16.1.1
services:

  redisdb1:
    image: redis:alpine
    container_name: redisdb1
    restart: unless-stopped
    ports:
      - "0.0.0.0:6379:6379/tcp"
    command: redis-server --save 20 1 --loglevel warning --requirepass MyPASS111
    volumes: 
      - ./redisdb1/data:/data
    networks:
      - services
