version: '3'
networks:
  services:
    name: services
    ipam:
      config:
        - subnet: 172.16.1.0/24
          ip_range: 172.16.1.0/24
          gateway: 172.16.1.1
services:
  gitlab:
    # image: gitlab/gitlab-ce:latest
    image: gitlab/gitlab-ce:16.9.2-ce.0
    container_name: gitlab
    restart: always
    hostname: 'MYDOMAIN'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://MYDOMAIN:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - '8929:8929'
      - '443:443'
      - '2424:2424'
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    shm_size: '2g'
    networks:
      - services

