version: '3'
networks:
  services:
    name: services
    ipam:
      config:
        - subnet: 172.16.1.0/24
          ip_range: 172.16.1.0/24
          gateway: 172.16.1.1
services:
  semaphore_db:
    image: mysql:lastest
    hostname: semaphore_db
    restart: unless-stopped
    volumes:
      - ./semaphore-mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=semaphore
      - MYSQL_USER=semaphore
      - MYSQL_PASSWORD=secret-password

  semaphore:
    container_name: semaphore
    image: semaphoreui/semaphore:latest
    ports:
      - 185:3000
    environment:
      - SEMAPHORE_DB_USER=semaphore
      - SEMAPHORE_DB_PASS=secret-password
      - SEMAPHORE_DB_HOST=semaphore_db
      - SEMAPHORE_DB_PORT=3306
      - SEMAPHORE_DB_DIALECT=mysql
      - SEMAPHORE_DB=semaphore
      - SEMAPHORE_PLAYBOOK_PATH=/tmp/semaphore/
      - SEMAPHORE_ADMIN_PASSWORD=semaphoreadmin
      - SEMAPHORE_ADMIN_NAME=semaphoreadmin
      - SEMAPHORE_ADMIN=semaphoreadmin
      - SEMAPHORE_ADMIN_EMAIL=admin@localhost
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION=  # access key encryption
      - ANSIBLE_HOST_KEY_CHECKING=false  # (optional)
    volumes:
      - ./inventory/:/inventory:ro
      - ./authorized-keys/:/authorized-keys:ro
      - ./config/:/etc/semaphore:rw
    restart: unless-stopped
    depends_on:
      - semaphore_db
