version: '3'
networks:
  services:
    name: services
    ipam:
      config:
        - subnet: 172.16.1.0/24
          ip_range: 172.16.1.0/24
          gateway: 172.16.1.1
services:
  wordpress1:
    image: wordpress:php8.2-apache
    restart: unless-stopped
    container_name: wordpress1
    ports:
    - "0.0.0.0:184:80"
    environment:
      WORDPRESS_DB_HOST: wordpressdb1
      WORDPRESS_DB_USER: DBUSER
      WORDPRESS_DB_PASSWORD: DBPASS
      WORDPRESS_DB_NAME: DBNAME
    volumes:
      - ./webhost/wordpress1/site:/var/www/html
    networks:
      - services

  wordpressdb1:
    image: mysql:5.7
    container_name: wordpressdb1
    restart: unless-stopped
    volumes:
      - ./webhost/wordpressdb1:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ROOTPASS
      MYSQL_USER: DBUSER
      MYSQL_DATABASE: DBNAME
      MYSQL_PASSWORD: DBPASS
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' , '--default-authentication-plugin=mysql_native_password']
    networks:
      - services