version: '3'
networks:
  services:
    name: services
    ipam:
      config:
        - subnet: 172.16.1.0/24
          ip_range: 172.16.1.0/24
          gateway: 172.16.1.1
services:

  wekandb:
    image: mongo:6
    container_name: wekandb
    restart: always
    command: mongod --logpath /dev/null --oplogSize 128 --quiet
    networks:
      - services
    expose:
      - 27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./wekan-db:/data/db
      - ./wekan-db-dump:/dump
  wekanapp:
    image: ghcr.io/wekan/wekan:latest
    container_name: wekanapp
    restart: unless-stopped
    networks:
      - services
    ports:
      - 0.0.0.0:192:8080
    environment:
      - WRITABLE_PATH=/data
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=http://localhost
      # - MAIL_URL=smtp://<mail_url>:25/?ignoreTLS=true&tls={rejectUnauthorized:false}
      # - MAIL_FROM=Wekan Notifications <noreply.wekan@mydomain.com>
      - WITH_API=true
      - RICHER_CARD_COMMENT_EDITOR=false
      - CARD_OPENED_WEBHOOK_ENABLED=false
      - BIGEVENTS_PATTERN=NONE
      - BROWSER_POLICY_ENABLED=true
    depends_on:
      - wekandb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./wekan-files:/data:rw
